import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
const output = fileURLToPath(
  new URL(
    "../../../supabase/functions/drive-gateway/generated/",
    import.meta.url,
  ),
);
await mkdir(output, { recursive: true });
for (const name of ["app", "db", "domain", "drive"]) {
  const compiled = await readFile(
    new URL(`../dist/${name}.js`, import.meta.url),
    "utf8",
  );
  await writeFile(
    join(output, `${name}.js`),
    "// Generated by npm run prepare:edge. Edit server/drive-gateway/src instead.\n" +
      compiled,
  );
}
console.log(
  "Prepared shared gateway implementation for Supabase Edge Runtime.",
);
